# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='mname',
            field=models.CharField(max_length=50, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=50, verbose_name='User'),
        ),
    ]
